# Generated by Django 6.0.4 on 2026-04-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated authors')),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('year', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
