# Generated by Django 6.0.4 on 2026-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
    ]
