# Generated by Django 6.0.4 on 2026-04-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-citation_count']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='abstract',
        ),
    ]
